title: "Maths en Moica"
description: "Ressources mathématiques pour tous les niveaux"
theme: jekyll-theme-primer
url: "https://mathsmoica.github.io"
baseurl: "/projet_BIB"

exclude:
  - venv/
  - .venv/
  - env/
  - .env/
  - bin/
  - lib/
  - include/
  - "*.py"
  - "*.pyc"
  - "*.sql"
  - "*.json"
  - "*.ipynb"
  - site/
  - path/
  - to/
  - .github/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - node_modules/
  - .gitignore

plugins:
  - jekyll-feed
  - jekyll-seo-tag

seo:
  title: "Maths en Moica"
  description: "Ressources mathématiques interactives"
