
title: "Maths en Moica"
description: "Ressources mathématiques pour tous les niveaux"
theme: jekyll-theme-primer
url: "https://mathsmoica.github.io"
baseurl: "/projet_BIB"

# Exclure les dossiers et fichiers inutiles
exclude:
  - venv/
  - .venv/
  - .github/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - node_modules/
  - .gitignore
  - "*.py"
  - "*.ipynb"

# Configuration des plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Paramètres SEO
seo:
  title: "Maths en Moica"
  description: "Ressources mathématiques interactives"